### PR TITLE
Fix plugin manage edit "plugin manager" scheme . permission

### LINKED ISSUE #1716: Plugin manager -Edit - wrong permission set for edit plugin manager .

### PR DESCRIPTION
**Pull request by orenyodfat**
Fix "plugin manager" Edit scheme  permission ,for the case editing the "PluginManager" it self 

fix #1716

### CODE REVIEW

File: src/lib/schemeUtils.ts [hunk 1]
```diff
@@ -148,6 +148,24 @@ export function schemeNameAndAddress(address: string) {
   }
 }
 
+/**
+ * given the address (of a scheme), return scheme's name
+ * @param  address [description]
+ * @return         [description]
+ */
+export function schemeNameFromAddress(address: string) {
```
Comment (dkent600) [inline src/lib/schemeUtils.ts:156]: Can you please refactor `schemeNameAndAddress` (just above) to use this new function?

File: src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx [hunk 2]
```diff
@@ -138,12 +138,18 @@ class CreateSchemeRegistrarProposal extends React.Component<IProps, IState> {
     } else {
       proposalType = IProposalType.SchemeRegistrarEdit;
     }
+
+    let permissionString = "0x" + permissions.toString(16).padStart(8, "0");
```
Comment (dkent600) [inline src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx:142]: Not a big deal, but I prefer an if/else or switch/case/default pattern here, to save an unnecessary assignment to `permissionString` when schemeName === "Plugin Manager"

Comment (dkent600) [reply src/components/Proposal/Create/SchemeForms/CreateSchemeRegistrarProposal.tsx:142]: Can you please add a comment in the code explaining why the special case hack is required?  Explaining why `permissions` is good for every scheme except "Plugin Manager".  This should not be the case, seems like a bug elsewhere.  Need to explain in the code.
