### PR TITLE
Cache management and other fixes

### LINKED ISSUE #400: Proposal Cards are not updated with latest state
To reproduce (there are different ways):

- Boost a proposal. It will move to boosted, but still show the "boost" button

### LINKED ISSUE #438: connection state warnings are alerts, should become notifications

### PR DESCRIPTION
**Pull request by jellegerbrandy**
- fix bug in calculating total rewards
- update client to 0.0.41, which as more aggrssive fetch policy - this fixes #400 
- use notifications for connection status instead of alerts - this fixes #438 
- restore linter triple-equals rule
- show notifications on proposal execute action [a first step towards implemeting #317

### CODE REVIEW

File: src/reducers/arcReducer.ts [hunk 1]
```diff
@@ -170,7 +170,7 @@ export interface IProposalState {
   state: ProposalStates;
   submittedTime: number;
   title: string;
-  transactionState: TransactionStates;
+  ITransactionState: TransactionStates;
```
Comment (tibetsprague) [inline src/reducers/arcReducer.ts]: this looks weird and maybe wrong

Comment (tibetsprague) [reply src/reducers/arcReducer.ts]: but we dont use this anymore...
