### PR TITLE
various fixes

### LINKED ISSUE #437: Only show the correct DAOs
**On staging** we only need to have two DAOs:
• one with the genesis params
• one identical to that, but with a fast proposal lifecycle.

**On mainnet** we will only need the actual Genesis DAO.

[Latest Genesis config params](https://docs.google.com/spreadsheets/d/1fkybRjRR4rO53gkpEhwA3Q2UjAlkIe3q7rrs0_bZFqI/edit#gid=293802003)

### LINKED ISSUE #476: update infura endpoints
https://blog.infura.io/infura-dashboard-transition-update-c670945a922a

### LINKED ISSUE #484: make the app work with MM in private mode

### PR DESCRIPTION
**Pull request by jellegerbrandy**
- add infura key, fixes #476
- show onlu indexed DAO on staging: fix #437 
- logic for connecting with Metamask: fixes #484

### CODE REVIEW

File: src/arc.ts [hunk 1]
```diff
@@ -122,6 +138,42 @@ export function checkNetwork(web3?: any) {
...
+/**
+ * check if the web3 connection is ready to send transactions, and warn the user if it is not
+ * @return true if things are fine, false if not
+ */
+export function checkNetworkAndWarn(showNotification?: any): boolean {
+  try {
+    checkNetwork();
+    return true;
+  } catch (err) {
+    // TODO: this should of course not be an alert, but a Modal
```
Comment (tibetsprague) [inline src/arc.ts]: Add a styling issue for this?

File: src/components/Account/AccountProfileContainer.tsx [hunk 2]
```diff
@@ -96,16 +95,18 @@ class AccountProfileContainer extends React.Component<IProps, null> {
...
     const web3 = await Util.getWeb3();
     const timestamp = new Date().getTime().toString();
-    const text = "Please sign this message to confirm your request to update your profile to name '" + values.name + "' and description '" + values.description + "'. There's no gas cost to you. Timestamp:" + timestamp;
+    const text = ("Please sign this message to confirm your request to update your profile to name '" +
+      values.name + "' and description '" + values.description +
+      "'. There's no gas cost to you. Timestamp:" + timestamp);
     const msg = ethUtil.bufferToHex(Buffer.from(text, "utf8"));
 
     const method = "personal_sign";
     // TODO: do we need promisify here? web3 1.0 supports promises natively
```
Comment (tibetsprague) [inline src/components/Account/AccountProfileContainer.tsx]: Remove comment
