### PR TITLE
fix CreateKnowGenericSchemeProposal - uint256 field should be rendered as "string" (not as "number")

### LINKED ISSUE #1507: Submit Proposal on ETHregistrar does not do anything
Screenshot 2020-03-13 at 17 57 52

nothing happens after clicking on submit proposal:

Screenshot 2020-03-13 at 18 15 47

### PR DESCRIPTION
**Pull request by orenyodfat**
fix #1507

### CODE REVIEW

File: src/genericSchemeRegistry/index.ts [hunk 1]
```diff
@@ -98,6 +98,11 @@ export class ActionField {
       userValue = userValue.trim();
     }
 
+    if (this.type == "uint256") {
+      return userValue.toString();
+    }
+    console.log(userValue.toString(),this.type);
```
Comment (tibetsprague) [inline src/genericSchemeRegistry/index.ts]: remove console.log

File: src/genericSchemeRegistry/index.ts [hunk 2]
```diff
@@ -98,6 +98,11 @@ export class ActionField {
       userValue = userValue.trim();
     }
 
+    if (this.type == "uint256") {
```
Comment (dkent600) [inline src/genericSchemeRegistry/index.ts]: Should be `===`

Comment (dkent600) [inline src/genericSchemeRegistry/index.ts]: Should confirm that this doesn't break anything.

Particularly:  What if `this.decimals` is set?  It won't be executed.
